### ISSUE TITLE
Some select fields have clear when hidden option some do not

### ISSUE THREAD

**Issue by SSDK-Hello** [team-forms/community#10]
Is it possible that the backend behavior of new select fields has changed and this hasn't been applied retroactively.

**Comment by Erin-Dwyer** [comment]
Hi @SSDK-Hello,

Thanks for raising this, from my testing it looks like the clear value when hidden is available for the "Drop-down menu" component but not for the "SharePoint Data" component. Would you mind confirming that is aligned with what you are reporting?

**Comment by SSDK-Hello** [comment]
So I believe I have worked out the discrepancy.

If you have a select field set to Hidden then the clear value on hidden option is hidden.

See attached

Is this intended behaviour?
[Clear on Hidden Field Debug.json](https://github.com/team-forms/community/files/14295492/Clear.on.Hidden.Field.Debug.json)

**Comment by Erin-Dwyer** [comment]
That is not the intended behaviour, however I believe has not been resolved in one of our recent releases :)
