### ISSUE TITLE
Date field format no visual only option

### ISSUE THREAD

**Issue by SSDK-Hello** [team-forms/community#12]
The Format option on datetime is described as controlling HOW the date is displayed. This isn't strictly true as it discards info to fit.

`For Example set the format of a date to MMM-yyyy and 17/04/2024 will evaluate to 01/04/2024 when transmitted via power automate if the format is left alone it works correctly.`

**Comment by Erin-Dwyer** [comment]
Hi @SSDK-Hello,

Would you mind providing an example [form source code](https://help.teamforms.app/en/articles/8711188-download-form-source-code) for this issue? When i try reproducing the issue the date is rendered using the provided format but the data remains stored in ISO8601 as shown in the image below.

![image](https://github.com/team-forms/community/assets/154988548/97b2a8a7-e71a-4b3d-a95f-bc4fd1aebdd3)

**Comment by SSDK-Hello** [comment]
Of course:

JSON attached

Steps to replicate

```
1. Put in a date mid month in my example I used 20th March 2024
2. Look at the submission info
```


It is submitted as

`   "dateTime": "2024-03-01T00:00:00+00:00",`
[Date Debug.json](https://github.com/team-forms/community/files/14295266/Date.Debug.json)

**Comment by Erin-Dwyer** [comment]
Hi @SSDK-Hello,

Thanks for the additional details, I can confirm that I am able to reproduce the behaviour you have described however it only occurs if the display format is a lower resolution to the resolution of the date you wish to store (e.g. display month/year of but want to store down to the day/month/year).

I'm not sure if this should be considered an issue/bug as there are many situations where it makes more sense to resolve the stored date to the first day of the month if you are only displaying the month/year. Are you able to share the use case to see if there a scenario where this should behave differently?

**Comment by SSDK-Hello** [comment]
Hi @Erin-Dwyer ,

Our plan was to store the full date resolution for use in a Power BI report but in turn only visually display Mon-Year in the form itself
