### ISSUE TITLE
Not calculating when hidden bug

### ISSUE THREAD

**Issue by SSDK-Hello** [team-forms/community#13]
RE: Project Task ID in data grid

[Example GUID.xlsx](https://github.com/team-forms/community/files/14296281/Example.GUID.xlsx)
[Not Calculating when hidden debug.json](https://github.com/team-forms/community/files/14296282/Not.Calculating.when.hidden.debug.json)

**Comment by SSDK-Hello** [comment]
For some unknown reason the value works correct if I add and hide another column which I set to the value of the original.

**Comment by Erin-Dwyer** [comment]
Hi @SSDK-Hello,

From your example it looks like you are setting the value directly using the instance object. This is not ideal as it can easily cause unwanted side effects (as you have experienced). The recommended way to achieve what your after would to instead set the value of the hidden text field using the method below:

1. Drag a hidden component into your form (or use a text field with "Clear Value When hidden" disabled)
2. Use the following expression in the **default value** field.

> Note the **default value** field is used instead of calculated value to prevent a new guid being generated each time the table renders. 

```javascript
value = crypto.randomUUID()
```
