### ISSUE TITLE
Deleted from data grid fields not fully deleted from JSON Schema hangs around via default value

### ISSUE THREAD

**Issue by SSDK-Hello** [team-forms/community#14]
See lines 28+:
[Not Calculating when hidden debug.json](https://github.com/team-forms/community/files/14296306/Not.Calculating.when.hidden.debug.json)

**Comment by Erin-Dwyer** [comment]
Hi @SSDK-Hello,

Thanks this is a known issue which should get fixed in a future release. We ill post updates on this issue here :) 
For now I do recommend manually removing the delete fields from the default value using the JSON editor.
