### ISSUE TITLE
Deleted Team Members still show up in user field

### ISSUE THREAD

**Issue by SSDK-Hello** [team-forms/community#15]
User field is set to team members not all and team members that have been removed are still showing.

This is also after manually refreshing and the user was deleted days ago.

**Comment by Erin-Dwyer** [comment]
Hi @SSDK-Hello,

When configuring the user compoent to "Team Members" Team Forms actually references the [User Information list](https://zimmergren.net/sharepoints-hidden-user-list-user-information-list/) in SharePoint. This is becuase the Microsoft Graph api for getting team member requires admin consent to call. 

Unfortunatly this list is managed by SharePoint and it appears that it does not automatically delete users when they are removed form the team. If you would like to remove a user you will need to remove them manually using the steps outlined in the article below:

https://www.sharepointdiary.com/2018/02/sharepoint-online-delete-user-from-user-information-list.html
