### ISSUE TITLE
Unique option does nothing

### ISSUE THREAD

**Issue by SSDK-Hello** [team-forms/community#16]
Tested with blank form attached
add 1 as text value submit
add 1 as text value submit

both are allowed
[unique-debug.json](https://github.com/team-forms/community/files/14431936/unique-debug.json)

**Comment by Erin-Dwyer** [comment]
Hi @SSDK-Hello,

Thanks for reporting your issue report. Your correct that the unique flag was not implemented, we have since removed this setting until such time as it has been implemented.

**Comment by AnthonyPhan** [comment]
Closed as removed from options
