### ISSUE TITLE
There's a problem syncing the data source.

### ISSUE THREAD

**Issue by glittery11** [team-forms/community#27]
![image](https://github.com/team-forms/community/assets/88357418/b8552077-75e7-4849-bc5c-7119f738b213)

I deleted a datasource and reconnected it, but something went wrong.
help me please.

**Comment by Erin-Dwyer** [comment]
Hi @glittery11 

I'll need a few more details to try and assist you here:
1. When you say you deleted the data source do you mean you deleted it form the data sources screen or did you delete the file/list form sharepoint?
2. What kind of data source are you using (e.g. SharePoint list, .json file, excel oline ect)

**Comment by Erin-Dwyer** [comment]
Could you also try manually syncing the data source using the steps outlined below to see if that resolves your error?

https://help.teamforms.app/en/articles/8044068-manually-refreshing-a-data-source

**Comment by glittery11** [comment]
@Erin-Dwyer Hi, thank you for your response.

1. I deleted the connection from the datasource list page in teamforms, the original list is there without any problem.
2. it is a sharepoint list.
3. Fortunately, I cleared my browser cache today and it's back to normal, but I'm still getting the error on device that I'm not sure how to clear the cache(like the in-app browser in teamforms on my iPad).

**Comment by Erin-Dwyer** [comment]
@glittery11 you can clear the local cache on you iPad/teams clients using the steps below:

1. Click the Team Forms setting icon. This is the cog icon in the top right-hand corner of the side bar. Its important to note this is different to the "[team settings](https://help.teamforms.app/en/articles/8319957-team-settings)".
     
    ![image](https://github.com/team-forms/community/assets/154988548/81788095-d915-442d-81a4-fc1f76cd2404)
    
    

2. Navigate to the "Storage" tab
3. Click "Delete Local Data"

These steps are also available in the help docs below :) 

https://help.teamforms.app/en/articles/8856838-troubleshooting-sync-issues
