### ISSUE TITLE
Allow Manual Override of Date Fields in Data Grid doesn't work

### ISSUE THREAD

**Issue by SSDK-Hello** [team-forms/community#8]
Setup includes:

Data Grid reading from a select dropdown to pre-populate a date field. I understand this is not ideal but it should still work. Essentially the override has no effect and the field resets to the original value.

![Animation](https://github.com/team-forms/community/assets/154335002/5a705724-90d7-4a29-95f9-842da0f66c20)

**Comment by Erin-Dwyer** [comment]
Hi @SSDK-Hello,

I think there might be some other logic in your form that may be causing the manually over write value to reset. Initial test appears to work fine. Would you mind providing a simplified example source code showing the issue? 

![2024-02-14 22 34 07](https://github.com/team-forms/community/assets/154988548/8873885d-2190-4818-9852-e2f7fc855e7d)

For you reference please i've attached the source code for my example above. You can import it into your environemnt using the method [outlined here](https://help.teamforms.app/en/articles/8413547-import-a-forms-source-code).

[Calculated Date Time in Data Grid.json](https://github.com/team-forms/community/files/14280981/Calculated.Date.Time.in.Data.Grid.json)

**Comment by SSDK-Hello** [comment]
As per (#9)

> Just note that setting the value variable only works for syncronous code, so if your working with promises this is not currently supported for the default value property.

Works when `value = output` is used in place of `instance.setValue(output);`
