### ISSUE TITLE
Default Value on a Date Field blank using same calculation that works when calculated

### ISSUE THREAD

**Issue by SSDK-Hello** [team-forms/community#9]
Setup includes:

Conversion from Excel Date to moment JS ie (Assuming excelTime is defined as reading from an excel doc)

```
var intermediateTime = excelTime - 25569;

var finalTime = intermediateTime * 86400;

var output = moment.unix(finalTime);

instance.setValue(output);
```

What works when calculated shows nothing when default value.

**Comment by Erin-Dwyer** [comment]
Hi @SSDK-Hello,

In not entirly sure how the excelTime variable in your example is set however when setting a default value you need to provide an expression which sets the value variable for the default value feature to work correctly. for example:

```
var intermediateTime = excelTime - 25569;
var finalTime = intermediateTime * 86400;
var output = moment.unix(finalTime);
value = output
```

Just note that setting the value variable only works for syncronous code, so if your working with promises this is not currently supported for the default value property.

**Comment by SSDK-Hello** [comment]
> Just note that setting the value variable only works for syncronous code, so if your working with promises this is not currently supported for the default value property.

Perfect, simply changing

`instance.setValue(output);`

to

`value = output`

has fixed my issue.

Good to know, thank you

**Comment by SSDK-Hello** [comment]
Sorry I stumbled upon my issues.

See attached what works as a calculated field fails as a default value.

[Default Date Debug.json](https://github.com/team-forms/community/files/14295853/Default.Date.Debug.json)
[Example Date.xlsx](https://github.com/team-forms/community/files/14295856/Example.Date.xlsx)
